<a href="https://colab.research.google.com/github/RushabhShahPrograms/Pytorch_tuts/blob/main/Pytorch_Tuts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

## List

In [ ]:
my_list = [[1,2,3,4,5],[6,7,8,9]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

## Numpy

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.49948806, 0.25396839, 0.12164184, 0.59037123],
       [0.18810429, 0.67011188, 0.16810374, 0.00300716],
       [0.95849906, 0.84093602, 0.19385461, 0.51635804]])

In [ ]:
np1.dtype

dtype('float64')

## Tensor

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.9764,  0.2810, -2.1365, -0.5399],
        [-1.0672, -0.8922,  1.0739, -0.5260],
        [-0.2944, -0.6370, -1.7232,  0.7081]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
my_tensort = torch.tensor(np1)
my_tensort

tensor([[0.4995, 0.2540, 0.1216, 0.5904],
        [0.1881, 0.6701, 0.1681, 0.0030],
        [0.9585, 0.8409, 0.1939, 0.5164]], dtype=torch.float64)

## tensor oops

In [ ]:
my_torch = torch.arange(10)

In [ ]:
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshape and view

my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# reshape if we don't know the number of items using -1
my_torch2 = torch.arange(15)
# my_torch2
my_torch2 = my_torch2.reshape(5,-1)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#with reshape and view, they will update

my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
# slices

my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch7[7]

tensor(7)

In [ ]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
# return column

my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

## Tensor math

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [ ]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# Reassignment
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_a

tensor([ 6,  8, 10, 12])

## Neural Network basic

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class Model(nn.Module):
  def __init__(self,in_features=4,h1=8,h2=9,out_features=3):
    super().__init__()
    self.fc1 = nn.Linear(in_features,h1)
    self.fc2 = nn.Linear(h1,h2)
    self.out = nn.Linear(h2,out_features)

  def forward(self,x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)

    return x

In [ ]:
torch.manual_seed(41)
model = Model()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd

In [ ]:
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
my_df = pd.read_csv(url)

In [ ]:
my_df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [ ]:
my_df['variety'] = my_df['variety'].replace('Setosa',0.0)
my_df['variety'] = my_df['variety'].replace('Versicolor',1.0)
my_df['variety'] = my_df['variety'].replace('Virginica',2.0)
my_df

sepal.length  sepal.width  petal.length  petal.width  variety
0             5.1          3.5           1.4          0.2      0.0
1             4.9          3.0           1.4          0.2      0.0
2             4.7          3.2           1.3          0.2      0.0
3             4.6          3.1           1.5          0.2      0.0
4             5.0          3.6           1.4          0.2      0.0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3      2.0
146           6.3          2.5           5.0          1.9      2.0
147           6.5          3.0           5.2          2.0      2.0
148           6.2          3.4           5.4          2.3      2.0
149           5.9          3.0           5.1          1.8      2.0

[150 rows x 5 columns]

In [ ]:
# Train test and split

X = my_df.drop('variety',axis=1)
y = my_df['variety']

In [ ]:
X = X.values
y = y.values

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

In [ ]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=0.01)

In [ ]:
epochs = 100
losses = []
for i in range(epochs):
  y_pred = model.forward(X_train)
  loss = criterion(y_pred,y_train)
  losses.append(loss.detach().numpy())
  if i % 10 == 0:
    print(f'Epoch:{i} and loss: {loss}')

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

Epoch:0 and loss: 0.046578045934438705
Epoch:10 and loss: 0.04843554645776749
Epoch:20 and loss: 0.048201337456703186
Epoch:30 and loss: 0.04729072004556656
Epoch:40 and loss: 0.04683079198002815
Epoch:50 and loss: 0.046583592891693115
Epoch:60 and loss: 0.04659406095743179
Epoch:70 and loss: 0.046587660908699036
Epoch:80 and loss: 0.04658295959234238
Epoch:90 and loss: 0.046583112329244614


In [ ]:
plt.plot(range(epochs),losses)
plt.ylabel("losses/error")
plt.xlabel('Epoch')

Text(0.5, 0, 'Epoch')