<a href="https://colab.research.google.com/github/RushabhShahPrograms/Pytorch_tuts/blob/main/PyTorch_Tuts_krish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.__version__

'2.2.1+cu121'

In [ ]:
import numpy as np

lst = [3,4,5,6]
arr = np.array(lst)

arr.dtype

dtype('int64')

# Convert numpy to pytorch tensors

In [ ]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [ ]:
tensors[:2]

tensor([3, 4])

In [ ]:
tensors[1:4]

tensor([4, 5, 6])

In [ ]:
tensors[3] = 100
tensors

tensor([  3,   4,   5, 100])

In [ ]:
arr

array([  3,   4,   5, 100])

In [ ]:
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100])

In [ ]:
tensor_arr[3] = 120
tensor_arr

tensor([  3,   4,   5, 120])

In [ ]:
arr

array([  3,   4,   5, 100])

In [ ]:
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [ ]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

# Arithmetic operations

In [ ]:
a = torch.tensor([3,4,5],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)
print(a+b)

tensor([ 7.,  9., 11.])


In [ ]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [ ]:
c = torch.zeros(3)

In [ ]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [ ]:
c

tensor([ 7.,  9., 11.])

In [ ]:
torch.add(a,b).sum()

tensor(27.)

In [ ]:
x = torch.tensor([3,4,5],dtype=torch.float)
y = torch.tensor([4,5,6],dtype=torch.float)

In [ ]:
x.mul(y)

tensor([12., 20., 30.])

In [ ]:
x.dot(y)

tensor(62.)

In [ ]:
x = torch.tensor([[1,4,2],[1,5,5]],dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]],dtype=torch.float)

In [ ]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [ ]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [ ]:
x@y

tensor([[55., 53.],
        [90., 92.]])

## backpropogation

In [ ]:
x = torch.tensor(4.0,requires_grad=True)
x

tensor(4., requires_grad=True)

In [ ]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [ ]:
# backpropogation

y.backward()
print(x.grad)

tensor(8.)


In [ ]:
lst = [[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]
torch_input = torch.tensor(lst,requires_grad=True)

In [ ]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [ ]:
y = torch_input**3 + torch_input**2
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [ ]:
z=y.sum()
z

tensor(1040., grad_fn=<SumBackward0>)

In [ ]:
z.backward()

In [ ]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])